name: build android apk 
on: [push] 
jobs:
build: 
runs-on: ubuntu-latest 
steps: 
- uses: actions/checkout@v3 
- uses: actions/setup-node@v3 
with:
 node-version: 18 
-run: npm install 
-run: npm run build 
-run: npx cap add android 
-run: npx cap copy 
-name: build apk 
run: cd android && ./gradlew assembledebug 
-uses: actions/upload-artifact@v3 
with: 
name: my-app-apk 
path: android/app/build/outputs/apk/debug/app-debug.apk